package entity;
// Generated Mar 24, 2017 7:27:14 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Image generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "IMAGE")
public class Image{

	private ImageId id;
	private Information information;

	public Image() {
	}

	public Image(ImageId id, Information information) {
		this.id = id;
		this.information = information;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "infor", column = @Column(name = "infor", nullable = false)),
			@AttributeOverride(name = "imageurl", column = @Column(name = "imageurl", nullable = false)) })
	public ImageId getId() {
		return this.id;
	}

	public void setId(ImageId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "infor", nullable = false, insertable = false, updatable = false)
	@XmlTransient
	public Information getInformation() {
		return this.information;
	}

	public void setInformation(Information information) {
		this.information = information;
	}

}
