package entity;
// Generated Mar 24, 2017 7:27:14 PM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Partner generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "PARTNER")
public class Partner{

	private int id;
	private String name;
	private Set<Information> informations = new HashSet<Information>(0);


	public Partner() {
	}

	public Partner(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Partner(int id, String name, Set<Information> informations) {
		this.id = id;
		this.name = name;
		this.informations = informations;
	
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partner")
	@XmlTransient
	public Set<Information> getInformations() {
		return this.informations;
	}

	public void setInformations(Set<Information> informations) {
		this.informations = informations;
	}



}
