package entity;
// Generated Mar 26, 2017 12:44:17 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

import entity.Information;
import entity.Users;

/**
 * Rating generated by hbm2java
 */
@Entity
@Table(name = "RATING")
public class Rating implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private RatingId id;
	private Information information;
	private Users users;

	public Rating() {
	}

	public Rating(RatingId id, Information information, Users users) {
		this.id = id;
		this.information = information;
		this.users = users;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "infor", column = @Column(name = "infor", nullable = false)),
			@AttributeOverride(name = "users", column = @Column(name = "users", nullable = false)) })
	public RatingId getId() {
		return this.id;
	}

	public void setId(RatingId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "infor", nullable = false, insertable = false, updatable = false)
	@XmlTransient
	public Information getInformation() {
		return this.information;
	}

	public void setInformation(Information information) {
		this.information = information;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "users", nullable = false, insertable = false, updatable = false)
	@XmlTransient
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
