package entity;
// Generated Mar 24, 2017 7:27:14 PM by Hibernate Tools 4.3.1.Final


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Room generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "ROOM")
public class Room {

	private int id;
	private Information information;
	private String type;
	private String detail;
	private String quanlity;
	private int maxpeople;
	private BigDecimal price;
	private Set<Booking> bookings = new HashSet<Booking>(0);


	public Room() {
	}

	public Room(int id, Information information, String type, int maxpeople, BigDecimal price) {
		this.id = id;
		this.information = information;
		this.type = type;
		this.maxpeople = maxpeople;
		this.price = price;
	}

	public Room(int id, Information information, String type, String detail, String quanlity,
			int maxpeople, BigDecimal price, Set<Booking> bookings) {
		this.id = id;
		this.information = information;
		this.type = type;
		this.detail = detail;
		this.quanlity = quanlity;
		this.maxpeople = maxpeople;
		this.price = price;
		this.bookings = bookings;

	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "infor", nullable = false)
	@XmlTransient
	public Information getInformation() {
		return this.information;
	}

	public void setInformation(Information information) {
		this.information = information;
	}

	@Column(name = "type", nullable = false)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "detail")
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "quanlity")
	public String getQuanlity() {
		return this.quanlity;
	}

	public void setQuanlity(String quanlity) {
		this.quanlity = quanlity;
	}

	@Column(name = "maxpeople", nullable = false)
	public int getMaxpeople() {
		return this.maxpeople;
	}

	public void setMaxpeople(int maxpeople) {
		this.maxpeople = maxpeople;
	}

	@Column(name = "price", nullable = false, scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "room")
	@XmlTransient
	public Set<Booking> getBookings() {
		return this.bookings;
	}

	public void setBookings(Set<Booking> bookings) {
		this.bookings = bookings;
	}

	
}
