package entity;
// Generated Mar 26, 2017 12:44:17 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

import entity.Information;
import entity.Service;

/**
 * Serviceinfor generated by hbm2java
 */
@Entity
@Table(name = "SERVICEINFOR")
public class Serviceinfor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ServiceinforId id;
	private Information information;
	private Service service;

	public Serviceinfor() {
	}

	public Serviceinfor(ServiceinforId id, Information information, Service service) {
		this.id = id;
		this.information = information;
		this.service = service;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "information", column = @Column(name = "information", nullable = false)),
			@AttributeOverride(name = "service", column = @Column(name = "service", nullable = false)) })
	public ServiceinforId getId() {
		return this.id;
	}

	public void setId(ServiceinforId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "information", nullable = false, insertable = false, updatable = false)
	@XmlTransient
	public Information getInformation() {
		return this.information;
	}

	public void setInformation(Information information) {
		this.information = information;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "service", nullable = false, insertable = false, updatable = false)
	@XmlTransient
	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

}
