package entity;
// Generated Mar 24, 2017 7:27:14 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Booking generated by hbm2java
 */
public class Booking {

	private int id;
	private Room room;
	private Users users;
	private Date datein;
	private String detail;
	private int quanlity;
	private Date dateout;

	public Booking() {
	}

	public Booking(int id, Room room, Users users, Date datein, int quanlity, Date dateout) {
		this.id = id;
		this.room = room;
		this.users = users;
		this.datein = datein;
		this.quanlity = quanlity;
		this.dateout = dateout;
	}

	public Booking(int id, Room room, Users users, Date datein, String detail, int quanlity, Date dateout) {
		this.id = id;
		this.room = room;
		this.users = users;
		this.datein = datein;
		this.detail = detail;
		this.quanlity = quanlity;
		this.dateout = dateout;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}
	public Date getDatein() {
		return this.datein;
	}

	public void setDatein(Date datein) {
		this.datein = datein;
	}

	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	public int getQuanlity() {
		return this.quanlity;
	}

	public void setQuanlity(int quanlity) {
		this.quanlity = quanlity;
	}
	public Date getDateout() {
		return this.dateout;
	}

	public void setDateout(Date dateout) {
		this.dateout = dateout;
	}

}
