package entity;
// Generated Mar 24, 2017 7:27:14 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * Food generated by hbm2java
 */
public class Food  {

	private int id;
	private Information information;
	private String detail;
	private String foodname;
	private BigDecimal price;
	private String image;

	public Food() {
	}

	public Food(int id, Information information, String foodname, BigDecimal price) {
		this.id = id;
		this.information = information;
		this.foodname = foodname;
		this.price = price;
	}

	public Food(int id, Information information, String detail, String foodname, BigDecimal price) {
		this.id = id;
		this.information = information;
		this.detail = detail;
		this.foodname = foodname;
		this.price = price;
	}
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}
	public Information getInformation() {
		return this.information;
	}

	public void setInformation(Information information) {
		this.information = information;
	}
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}
	public String getFoodname() {
		return this.foodname;
	}

	public void setFoodname(String foodname) {
		this.foodname = foodname;
	}
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

}
